"use client";

import { FormEvent, useState, useTransition, type ReactNode } from "react";
import { AUTOMATION_ACTIONS, AUTOMATION_TRIGGERS, actionMeta, triggerMeta, type AutomationActionType, type AutomationTrigger } from "@/lib/automation-types";
import { OPPORTUNITY_STATUSES, PIPELINE_STAGES, STAGE_LABELS } from "@/lib/pipeline";
import { addWorkflowAction, configureWorkflowAction, createWorkflow, deleteWorkflowAction, seedAutomationTemplates, setWorkflowPublished, testWorkflow, updateWorkflowTrigger } from "./actions";

type ActionSeed = { id: string; type: AutomationActionType; targetStage: string | null; targetStatus: string | null; message: string | null };
export type AutomationWorkflowSeed = { id: string; name: string; description: string | null; trigger: AutomationTrigger; isPublished: boolean; updatedAt: string; actions: ActionSeed[]; runs: { id: string; summary: string; createdAt: string; guestName: string }[] };

const groups = ["Oportunidades", "Cotizaciones", "Pagos", "Estancias"];

export function AutomationManager({ workflows, reservations }: { workflows: AutomationWorkflowSeed[]; reservations: { id: string; label: string }[] }) {
  const [selectedId, setSelectedId] = useState<string | null>(workflows[0]?.id ?? null);
  const [query, setQuery] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [panel, setPanel] = useState<"trigger" | "action" | null>(null);
  const [tab, setTab] = useState<"builder" | "settings" | "history" | "logs">("builder");
  const [pending, startTransition] = useTransition();
  const selected = workflows.find((workflow) => workflow.id === selectedId) ?? null;
  const filtered = workflows.filter((workflow) => workflow.name.toLowerCase().includes(query.toLowerCase()));

  function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    startTransition(async () => { const id = await createWorkflow(form); setSelectedId(id); setCreateOpen(false); });
  }

  if (!selected) return <main className="min-w-0 flex-1 overflow-y-auto p-8"><header className="mx-auto flex max-w-[1500px] flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase text-ink/35">Ventas · Operación</p><h1 className="mt-1 font-display text-4xl font-extrabold">Automatizaciones</h1><p className="mt-2 text-sm text-ink/50">Conecta pagos, cotizaciones y estancias con el pipeline.</p></div><button type="button" onClick={() => startTransition(() => seedAutomationTemplates())} className="rounded-md bg-ink px-4 py-2.5 text-sm font-bold text-white">Cargar reglas base</button></header><EmptyCreate open={createOpen} setOpen={setCreateOpen} onSubmit={create} pending={pending} /></main>;

  return <main className="relative min-w-0 flex-1 overflow-hidden bg-[#f4f6fa]">
    <div className="flex h-full min-w-[980px]">
      <section className="flex w-[320px] shrink-0 flex-col border-r border-ink/10 bg-white">
        <div className="border-b border-ink/10 p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase text-ink/35">Automatización</p><h1 className="mt-1 font-display text-2xl font-extrabold">Workflows</h1></div><button type="button" onClick={() => setCreateOpen(true)} className="grid h-9 w-9 place-items-center rounded-md bg-[#2468ec] text-xl font-medium text-white" title="Crear workflow">+</button></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar workflows" className="mt-4 h-10 w-full rounded-md border border-ink/15 bg-white px-3 text-sm outline-none focus:border-[#2468ec]" /></div>
        <div className="border-b border-ink/10 px-5 py-3 text-xs font-bold text-ink/45">{filtered.length} workflows</div>
        <div className="min-h-0 flex-1 overflow-y-auto p-2">{filtered.map((workflow) => <button key={workflow.id} type="button" onClick={() => { setSelectedId(workflow.id); setPanel(null); }} className={`mb-1 w-full rounded-md border p-3 text-left transition ${workflow.id === selected.id ? "border-[#2468ec] bg-[#edf4ff]" : "border-transparent hover:border-ink/10 hover:bg-ink/[0.025]"}`}><div className="flex items-start justify-between gap-2"><p className="font-bold">{workflow.name}</p><span className={`rounded px-1.5 py-0.5 text-[10px] font-bold ${workflow.isPublished ? "bg-emerald-50 text-emerald-700" : "bg-ink/5 text-ink/45"}`}>{workflow.isPublished ? "Activa" : "Borrador"}</span></div><p className="mt-1 text-xs text-ink/45">{triggerMeta[workflow.trigger].label}</p><p className="mt-2 text-[11px] text-ink/35">{workflow.actions.length} acción(es)</p></button>)}</div>
        <button type="button" disabled={pending} onClick={() => startTransition(() => seedAutomationTemplates())} className="m-3 rounded-md border border-ink/15 px-3 py-2 text-xs font-bold text-ink/70 hover:bg-ink/[0.03]">Cargar reglas base</button>
      </section>

      <section className="relative flex min-w-0 flex-1 flex-col overflow-hidden">
        <header className="flex h-[72px] shrink-0 items-center justify-between border-b border-ink/10 bg-white px-7"><div><p className="text-xs font-bold uppercase text-ink/35">Workflow</p><h2 className="mt-0.5 text-xl font-extrabold">{selected.name}</h2></div><div className="flex items-center gap-3"><button type="button" onClick={() => startTransition(async () => { await testWorkflow(selected.id, reservations[0]?.id ?? ""); })} disabled={pending || !reservations.length} className="rounded-md border border-[#2468ec]/30 px-3 py-2 text-sm font-bold text-[#2468ec] disabled:opacity-40">Probar workflow</button><label className="flex items-center gap-2 text-sm font-bold"><span className="text-ink/55">{selected.isPublished ? "Publicada" : "Borrador"}</span><input type="checkbox" checked={selected.isPublished} onChange={(event) => startTransition(() => setWorkflowPublished(selected.id, event.target.checked))} className="h-5 w-9 accent-[#2468ec]" /></label></div></header>
        <nav className="flex h-12 shrink-0 items-center gap-7 border-b border-ink/10 bg-white px-7 text-sm font-bold text-ink/50">{([['builder','Constructor'], ['settings','Configuración'], ['history','Historial'], ['logs','Registros']] as const).map(([key,label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`h-full border-b-2 ${tab === key ? "border-[#2468ec] text-[#2468ec]" : "border-transparent"}`}>{label}</button>)}</nav>
        {tab === "builder" ? <Builder workflow={selected} openPanel={setPanel} pending={pending} onConfigure={(id, data) => startTransition(() => configureWorkflowAction(id, data))} onDelete={(id) => startTransition(() => deleteWorkflowAction(id))} /> : <WorkflowInfo workflow={selected} tab={tab} />}
      </section>

      {panel && <PickerPanel mode={panel} close={() => setPanel(null)} onTrigger={(trigger) => { startTransition(() => updateWorkflowTrigger(selected.id, trigger)); setPanel(null); }} onAction={(type) => { startTransition(() => addWorkflowAction(selected.id, type)); setPanel(null); }} />}
    </div>
    <EmptyCreate open={createOpen} setOpen={setCreateOpen} onSubmit={create} pending={pending} />
  </main>;
}

function Builder({ workflow, openPanel, pending, onConfigure, onDelete }: { workflow: AutomationWorkflowSeed; openPanel: (panel: "trigger" | "action") => void; pending: boolean; onConfigure: (id: string, data: { targetStage?: string; targetStatus?: string; message?: string }) => void; onDelete: (id: string) => void }) {
  return <div className="relative min-h-0 flex-1 overflow-auto bg-[linear-gradient(rgba(17,17,17,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(17,17,17,.035)_1px,transparent_1px)] bg-[size:24px_24px] p-10"><div className="absolute right-6 top-5"><button type="button" onClick={() => openPanel("action")} className="rounded-md bg-white px-4 py-2 text-sm font-bold shadow-sm ring-1 ring-ink/10">+ Añadir</button></div><div className="mx-auto flex max-w-[560px] flex-col items-center pt-12"><WorkflowNode eyebrow="DISPARADOR" title={triggerMeta[workflow.trigger].label} detail={triggerMeta[workflow.trigger].description} accent="#2468ec" action={<button type="button" onClick={() => openPanel("trigger")} className="text-xs font-bold text-[#2468ec]">Cambiar</button>} /><Connector /><div className="space-y-4">{workflow.actions.map((action, index) => <div key={action.id} className="flex flex-col items-center"><ActionNode action={action} index={index} pending={pending} onConfigure={onConfigure} onDelete={onDelete} />{index < workflow.actions.length - 1 && <Connector />}</div>)}</div><button type="button" onClick={() => openPanel("action")} className="mt-5 grid h-10 w-10 place-items-center rounded-full border-2 border-dashed border-[#2468ec]/50 bg-white text-xl text-[#2468ec]">+</button><div className="mt-5 rounded-full bg-ink/10 px-3 py-1 text-[10px] font-bold uppercase text-ink/45">Fin</div></div></div>;
}

function WorkflowNode({ eyebrow, title, detail, accent, action }: { eyebrow: string; title: string; detail: string; accent: string; action?: ReactNode }) { return <div className="w-[420px] rounded-md border bg-white shadow-[0_12px_30px_rgba(17,17,17,.08)]" style={{ borderColor: accent }}><div className="h-1 rounded-t-md" style={{ backgroundColor: accent }} /><div className="flex items-start gap-3 p-4"><span className="grid h-9 w-9 place-items-center rounded-md text-base font-bold text-white" style={{ backgroundColor: accent }}>↗</span><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase text-ink/40">{eyebrow}</p><p className="mt-1 font-bold">{title}</p><p className="mt-1 text-xs leading-relaxed text-ink/50">{detail}</p></div>{action}</div></div>; }
function Connector() { return <div className="h-8 w-px bg-[#9fb1ca]" />; }
function ActionNode({ action, index, pending, onConfigure, onDelete }: { action: ActionSeed; index: number; pending: boolean; onConfigure: (id: string, data: { targetStage?: string; targetStatus?: string; message?: string }) => void; onDelete: (id: string) => void }) { const meta = actionMeta[action.type]; return <div className="w-[420px] rounded-md border border-ink/15 bg-white shadow-[0_8px_22px_rgba(17,17,17,.06)]"><div className="flex items-start gap-3 p-4"><span className="grid h-9 w-9 place-items-center rounded-md bg-[#f0eaff] text-base font-bold text-[#7752cf]">{index + 1}</span><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase text-ink/40">ACCIÓN</p><p className="mt-1 font-bold">{meta.label}</p><p className="mt-1 text-xs text-ink/50">{meta.description}</p>{action.type === "MOVE_STAGE" && <select defaultValue={action.targetStage ?? ""} onChange={(event) => onConfigure(action.id, { targetStage: event.target.value })} disabled={pending} className="mt-3 h-9 w-full rounded-md border border-ink/15 bg-white px-2 text-xs font-semibold"><option value="">Seleccionar etapa</option>{PIPELINE_STAGES.map((stage) => <option key={stage} value={stage}>{STAGE_LABELS.es[stage]}</option>)}</select>}{action.type === "SET_STATUS" && <select defaultValue={action.targetStatus ?? ""} onChange={(event) => onConfigure(action.id, { targetStatus: event.target.value })} disabled={pending} className="mt-3 h-9 w-full rounded-md border border-ink/15 bg-white px-2 text-xs font-semibold"><option value="">Seleccionar estado</option>{OPPORTUNITY_STATUSES.map((status) => <option key={status} value={status}>{({ OPEN: "Abierta", WON: "Ganada", LOST: "Perdida", ABANDONED: "Abandonada" })[status]}</option>)}</select>}{(action.type === "SEND_MESSAGE" || action.type === "CREATE_TASK") && <input defaultValue={action.message ?? ""} onBlur={(event) => onConfigure(action.id, { message: event.target.value })} placeholder={action.type === "SEND_MESSAGE" ? "Mensaje automático" : "Título de tarea"} className="mt-3 h-9 w-full rounded-md border border-ink/15 px-2 text-xs" />}</div><button type="button" onClick={() => onDelete(action.id)} className="text-lg text-ink/35 hover:text-red-600" title="Eliminar acción">×</button></div></div>; }

function PickerPanel({ mode, close, onTrigger, onAction }: { mode: "trigger" | "action"; close: () => void; onTrigger: (trigger: AutomationTrigger) => void; onAction: (action: AutomationActionType) => void }) { const [query, setQuery] = useState(""); const options = mode === "trigger" ? AUTOMATION_TRIGGERS : AUTOMATION_ACTIONS; const matches = options.filter((key) => (mode === "trigger" ? triggerMeta[key as AutomationTrigger].label : actionMeta[key as AutomationActionType].label).toLowerCase().includes(query.toLowerCase())); return <aside className="z-20 flex w-[390px] shrink-0 flex-col border-l border-ink/10 bg-white shadow-[-12px_0_30px_rgba(17,17,17,.08)]"><div className="flex items-center justify-between border-b border-ink/10 p-5"><h3 className="text-lg font-extrabold">{mode === "trigger" ? "Añadir disparador" : "Añadir acción"}</h3><button type="button" onClick={close} className="text-2xl text-ink/50">×</button></div><div className="p-4"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar" className="h-10 w-full rounded-md border border-[#2468ec] px-3 text-sm outline-none" /></div><div className="min-h-0 flex-1 overflow-y-auto px-4 pb-6">{mode === "trigger" ? groups.map((group) => { const items = matches.filter((key) => triggerMeta[key as AutomationTrigger].group === group); if (!items.length) return null; return <div key={group} className="mb-5"><p className="mb-2 text-xs font-bold uppercase text-ink/40">{group}</p>{items.map((key) => <button key={key} type="button" onClick={() => onTrigger(key as AutomationTrigger)} className="mb-1 w-full rounded-md border border-ink/10 p-3 text-left hover:border-[#2468ec] hover:bg-[#edf4ff]"><p className="font-bold">{triggerMeta[key as AutomationTrigger].label}</p><p className="mt-1 text-xs text-ink/50">{triggerMeta[key as AutomationTrigger].description}</p></button>)}</div>; }) : matches.map((key) => <button key={key} type="button" onClick={() => onAction(key as AutomationActionType)} className="mb-2 w-full rounded-md border border-ink/10 p-3 text-left hover:border-[#2468ec] hover:bg-[#edf4ff]"><p className="font-bold">{actionMeta[key as AutomationActionType].label}</p><p className="mt-1 text-xs text-ink/50">{actionMeta[key as AutomationActionType].description}</p></button>)}</div></aside>; }

function WorkflowInfo({ workflow, tab }: { workflow: AutomationWorkflowSeed; tab: "settings" | "history" | "logs" }) { return <div className="min-h-0 flex-1 overflow-y-auto p-8"><div className="mx-auto max-w-3xl rounded-md border border-ink/10 bg-white p-6">{tab === "settings" && <><h3 className="text-xl font-extrabold">Configuración</h3><p className="mt-2 text-sm text-ink/55">{workflow.description || "Sin descripción"}</p><div className="mt-6 rounded-md bg-[#f4f7fb] p-4 text-sm"><strong>Disparador:</strong> {triggerMeta[workflow.trigger].label}<br /><strong>Estado:</strong> {workflow.isPublished ? "Publicada y activa" : "Borrador"}</div></>}{tab === "history" && <><h3 className="text-xl font-extrabold">Historial de inscripción</h3><p className="mt-2 text-sm text-ink/50">Cada registro muestra una oportunidad que activó este workflow.</p><RunList runs={workflow.runs} /></>}{tab === "logs" && <><h3 className="text-xl font-extrabold">Registros de ejecución</h3><RunList runs={workflow.runs} /></>}</div></div>; }
function RunList({ runs }: { runs: AutomationWorkflowSeed["runs"] }) { return <div className="mt-6 divide-y divide-ink/10 rounded-md border border-ink/10">{runs.length ? runs.map((run) => <div key={run.id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-bold">{run.guestName}</p><p className="mt-1 text-xs text-ink/50">{run.summary}</p></div><time className="text-xs text-ink/40">{new Date(run.createdAt).toLocaleString("es-MX")}</time></div>) : <p className="p-8 text-center text-sm text-ink/45">Aún no hay ejecuciones.</p>}</div>; }
function EmptyCreate({ open, setOpen, onSubmit, pending }: { open: boolean; setOpen: (open: boolean) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; pending: boolean }) { return <>{!open && <button type="button" onClick={() => setOpen(true)} className="mx-auto mt-8 block rounded-md bg-[#2468ec] px-5 py-3 text-sm font-bold text-white">+ Crear workflow</button>}{open && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/35 p-4"><form onSubmit={onSubmit} className="w-full max-w-md rounded-md bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold">Nuevo workflow</h2><button type="button" onClick={() => setOpen(false)} className="text-2xl text-ink/40">×</button></div><label className="mt-5 block text-sm font-bold">Nombre<input name="name" required placeholder="Ej. Seguimiento de cotización" className="mt-2 h-10 w-full rounded-md border border-ink/15 px-3 font-normal" /></label><label className="mt-4 block text-sm font-bold">Disparador<select name="trigger" className="mt-2 h-10 w-full rounded-md border border-ink/15 bg-white px-3 font-normal">{AUTOMATION_TRIGGERS.map((trigger) => <option key={trigger} value={trigger}>{triggerMeta[trigger].label}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Descripción<textarea name="description" className="mt-2 min-h-20 w-full rounded-md border border-ink/15 p-3 font-normal" /></label><button disabled={pending} className="mt-5 h-10 w-full rounded-md bg-[#2468ec] text-sm font-bold text-white disabled:opacity-50">Crear workflow</button></form></div>}</>; }
