import { db } from "@/lib/db";
import { Sidebar } from "../../sidebar";
import { CommercialHeader } from "../commercial-header";

export const dynamic = "force-dynamic";
const money = (value: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" }).format(value);
const statusLabels = { PENDING: "Pendiente", PAID: "Pagada", REFUNDED: "Reembolsada", VOID: "Anulada" } as const;
const channelLabels = { PLATFORM: "Plataforma", POS: "Punto de venta", FRONT_DESK: "Recepción", OTA: "OTA", OTHER: "Otro" } as const;

export default async function OrdersPage() {
  const sales = await db.sale.findMany({ include: { guest: true, reservation: { include: { property: true } }, lines: true }, orderBy: { createdAt: "desc" }, take: 100 });
  const total = sales.filter((sale) => sale.status === "PAID").reduce((sum, sale) => sum + sale.total, 0);
  return <div className="flex h-screen overflow-hidden bg-[#f6f7f9]"><Sidebar active="/dashboard/ventas/ordenes" /><main className="min-w-0 flex-1 overflow-y-auto"><CommercialHeader active="/dashboard/ventas/ordenes" title="Ventas y órdenes" subtitle="Ingresos consolidados de reservas, recepción y punto de venta." /><div className="mx-auto max-w-[1500px] p-8"><div className="mb-5 grid gap-4 sm:grid-cols-3"><div className="rounded-md border border-ink/10 bg-white p-5"><p className="text-xs font-bold uppercase text-ink/40">Ventas registradas</p><p className="mt-2 text-2xl font-extrabold">{sales.length}</p></div><div className="rounded-md border border-ink/10 bg-white p-5"><p className="text-xs font-bold uppercase text-ink/40">Ingresos cobrados</p><p className="mt-2 text-2xl font-extrabold">{money(total)}</p></div><div className="rounded-md border border-ink/10 bg-white p-5"><p className="text-xs font-bold uppercase text-ink/40">Ticket promedio</p><p className="mt-2 text-2xl font-extrabold">{money(total / Math.max(1, sales.filter((sale) => sale.status === "PAID").length))}</p></div></div><section className="overflow-hidden rounded-md border border-ink/10 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-ink/[0.025] text-xs uppercase text-ink/40"><tr><th className="px-5 py-3">Orden</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Origen</th><th className="px-4 py-3">Conceptos</th><th className="px-4 py-3">Estado</th><th className="px-5 py-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-ink/10">{sales.map((sale) => <tr key={sale.id}><td className="px-5 py-4"><strong>{sale.number}</strong><p className="mt-1 text-xs text-ink/40">{sale.createdAt.toLocaleDateString("es-MX")}</p></td><td className="px-4 py-4">{sale.guest?.name ?? "Venta mostrador"}<p className="mt-1 text-xs text-ink/40">{sale.reservation?.property.name ?? "Sin reserva"}</p></td><td className="px-4 py-4">{channelLabels[sale.channel]}</td><td className="max-w-80 px-4 py-4"><p className="truncate">{sale.lines.map((line) => line.itemName).join(", ")}</p><p className="mt-1 text-xs text-ink/40">{sale.lines.length} renglones</p></td><td className="px-4 py-4"><span className={`rounded px-2 py-1 text-xs font-bold ${sale.status === "PAID" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{statusLabels[sale.status]}</span></td><td className="px-5 py-4 text-right font-bold">{money(sale.total)}</td></tr>)}</tbody></table></div></section></div></main></div>;
}
